POST http://localhost:3000/users/login
content-type: application/json

{
    "username": "jaed",
    "password": "password"
}


###

GET http://localhost:3000/users/logout

###

GET http://localhost:3000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmM3NGZlZmJiYTFlY2Y5NDcxZDA3NzYiLCJpYXQiOjE2NTc4OTgwNjIsImV4cCI6MTY1NzkwMTY2Mn0.LtxfeNYQI8YP6WDxgKz482rq_tNcoxeatGDLDkTBIZs

###

GET http://localhost:3000/test/todos
